import { textColors } from "../../../../styles/variables";
export const LinksArray = [
  {
    id: "news",
    icon: "document",
    iconSize: "1.25rem",
    iconColor: textColors["400"],
    text: "news.blog",
    textColor: textColors["400"],
    textSize: "1rem",
    line: "1.25rem",
    href: "/",
  },
  {
    id: "chat",
    icon: "chat",
    iconSize: "1.25rem",
    iconColor: textColors["400"],
    text: "community.forums",
    textColor: textColors["400"],
    textSize: "1rem",
    line: "1.25rem",
    href: "/community-forums",
  },
  {
    id: "notebook",
    icon: "notebook",
    iconSize: "1.25rem",
    iconColor: textColors["400"],
    text: "dictionary",
    textColor: textColors["400"],
    textSize: "1rem",
    line: "1.25rem",
    href: "/dictionary",
  },
  {
    id: "puzzle",
    icon: "pazzle",
    iconSize: "1.25rem",
    iconColor: textColors["400"],
    text: "puzzles",
    textColor: textColors["400"],
    textSize: "1rem",
    line: "1.25rem",
    href: "/puzzles",
  },
  {
    id: "shop",
    icon: "shop",
    iconSize: "1.25rem",
    iconColor: textColors["400"],
    text: "shop",
    textColor: textColors["400"],
    textSize: "1rem",
    line: "1.25rem",
    href: "/shop",
  },
];
